steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/microservices-store-449702/registry-image/products-ms-prod",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/microservices-store-449702/registry-image/products-ms-prod",
      ]
options:
  logging: CLOUD_LOGGING_ONLY